name: 'When communities directory changes, update frontmatter .md files'
true:
  push:
    paths:
      - communities/*.txt
  workflow_dispatch:
concurrency:
  cancel-in-progress: true
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
jobs:
  copy-to-site-repo:
    needs:
      - frontmatter
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: wikipathways-database
          submodules: true
      - name: Checkout jekyll repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: wikipathways.github.io
          repository: wikipathways/wikipathways.github.io
          ssh-key: '${{ secrets.ACTIONS_DEPLOY_KEY }}'
          submodules: true
      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: '${{ secrets.ACTIONS_DEPLOY_KEY }}'
      - name: Commit report
        run: |-
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          cp wikipathways-database/pathways/*/*.md wikipathways.github.io/_pathways/
          cd wikipathways.github.io
          git add _pathways/*.md
          if git diff --exit-code --staged > /dev/null; then
              echo "No changes"
          else
              git commit -m 'Update communities in md files'
              git push
          fi
  frontmatter:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: wikipathways-database
          submodules: true
      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: '${{ secrets.ACTIONS_DEPLOY_KEY }}'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install deps
        run: "pip install python-frontmatter\n"
      - name: Update communities in frontmatter
        run: "python ./scripts/update_frontmatter_communities.py\n"
      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add pathways/*/*.md
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git commit -m 'Update communities in frontmatter .md files'
              git push
          fi
