name: GPML added or edited. Process updates to sync.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - pathways/**/*.gpml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  # inspired by https://dev.to/scienta/get-changed-files-in-github-actions-1p36
  changed-files:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      gpml: ${{ steps.changes.outputs.gpml }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "GPML files added/changed between github.event.before ${{ github.event.before }} and github.sha ${{ github.sha }} (now)"
          #echo "github.event.after ${{ github.event.after }}"
          git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.sha }} | grep .gpml$
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.sha }} | xargs)"
          echo "::set-output name=gpml::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.sha }} | grep .gpml$ | xargs)"
  
  metadata:
    runs-on: ubuntu-latest
    needs: changed-files
    steps:
      - name: Checkout wikipathways-database repo
        uses: actions/checkout@v2
        
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          
      - name: Install deps
        run: |
          wget https://github.com/PathVisio/pathvisio/releases/download/v3.3.0/pathvisio_bin-3.3.0.zip
          unzip pathvisio_bin-3.3.0.zip

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/pathvisio-3.3.0
          key: ${{ runner.os }}-java-${{ hashFiles('pathvisio.jar') }}
          restore-keys: |
            ${{ runner.os }}-java-
            
      - name: Demo step for a demo job showing use of Java
        run: |
          # TODO: this is currently just a placeholder to show a java program.
          # Change this to use https://github.com/wikipathways/meta-data-action
          # instead of pathvisio. 
          for f in ${{needs.changed-files.outputs.gpml}}; do
            wpid="$(basename ""$f"" | sed 's/.gpml//')"
            echo "generating info and datanode files for $wpid ($f)"
            sh ./pathvisio-3.3.0/pathvisio.sh -v
          done
          
  pubmed:
    runs-on: ubuntu-20.04
    needs: [changed-files, metadata]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - working-directory: scripts/generate-references
        run: |
          npm install
          node index.js

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add pathways/*/*-bibliography.tsv
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git pull
              git commit -m 'Update formatted references'
              git push
          fi
          
  frontmatter:
    runs-on: ubuntu-20.04
    needs: [changed-files, metadata]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}   ## for push into cookbook-dev

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install deps
        run: |
          pip install python-frontmatter
          
      - name: Create pathway frontmatter
        run: |        
          for f in ${{needs.changed-files.outputs.gpml}}; do
            wpid="$(basename ""$f"" | sed 's/.gpml//')"
            echo "generating frontmatter file for $wpid"
            json_info_f=./pathways/"$wpid"/"$wpid"-info.json
            old_info_f=./pathways/"$wpid"/"$wpid".info
            if [ -e "$json_info_f" ]; then
              python scripts/create_pathway_frontmatter.py "$json_info_f"
            elif [ -e "$old_info_f" ]; then
              python scripts/create_pathway_frontmatter.py "$old_info_f"
            else
              echo "info file missing for $wpid" >2
            fi
          done

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add pathways/*/*.md
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git pull
              git commit -m 'Update frontmatter .md files'
              git push
          fi
          
  sync-site-repo:
    runs-on: ubuntu-20.04
    needs: [metadata, pubmed, frontmatter]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: wikipathways-database
          submodules: true
          fetch-depth: 0
          
      - name: Checkout jekyll repo
        uses: actions/checkout@v2
        with:
          repository: wikipathways/wikipathways.github.io
          path: wikipathways.github.io
          submodules: true
          fetch-depth: 0
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}   ## for push into cookbook-dev

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          cp wikipathways-database/pathways/*/*.md wikipathways.github.io/_pathways/
          cp wikipathways-database/pathways/*/*-bibliography.tsv wikipathways.github.io/_data/
          cp wikipathways-database/pathways/*/*-datanodes.tsv wikipathways.github.io/_data/
          cd wikipathways.github.io
          git add _pathways/*.md
          git add _data/*.tsv
          if git diff --exit-code --staged > /dev/null; then
              echo "No changes"
          else
              git commit -m 'Update tsv and md files'
              git push
          fi
