name: GPML deleted. Sync repo(s) in response.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - pathways/**/*.gpml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  # from https://dev.to/scienta/get-changed-files-in-github-actions-1p36
  deleted-files:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      gpml: ${{ steps.changes.outputs.gpml }}
      shas: ${{ steps.changes.outputs.shas }}
      test: ${{ steps.changes.outputs.test }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=test::hello"
          echo "::set-output name=shas::${{ github.event.push.base.sha }} ${{ github.sha }}"
          #echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRTD ${{ github.event.push.before }} ${{ github.event.push.after }} | xargs)"
          echo "${{ github.event.push.before }} vs. ${{ github.event.push.after }} vs. ${{ github.sha }}"
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRTD ${{ github.event.push.before }} ${{ github.sha }} | xargs)"
          echo "::set-output name=gpml::$(git diff --name-only --diff-filter=D ${{ github.event.push.before }} ${{ github.sha }} | grep .gpml$ | xargs)"
          
  sync-site-repo:
    runs-on: ubuntu-latest
    needs: deleted-files
    # only run there are changed files
    #if: ${{needs.deleted-files.outputs.gpml}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: wikipathways-database
          submodules: true
          fetch-depth: 0
          
      - name: Checkout jekyll repo
        uses: actions/checkout@v2
        with:
          repository: wikipathways/wikipathways.github.io
          path: wikipathways.github.io
          submodules: true
          fetch-depth: 0
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}   ## for push into cookbook-dev

      - name: Commit report
        run: |
          echo 'all:'
          echo ${{needs.deleted-files.outputs.all}}
          echo 'deleted gpmls:'
          echo ${{needs.deleted-files.outputs.gpml}}
          echo 'test output:'
          echo ${{needs.deleted-files.outputs.test}}
          echo 'shas output:'
          echo ${{needs.deleted-files.outputs.shas}}
          #git config --global user.name 'GitHub Action'
          #git config --global user.email 'action@github.com'
          #cp wikipathways-database/pathways/*/*.md wikipathways.github.io/_pathways/
          #cp wikipathways-database/pathways/*/*-bibliography.tsv wikipathways.github.io/_data/
          #cp wikipathways-database/pathways/*/*-datanodes.tsv wikipathways.github.io/_data/
          #cd wikipathways.github.io
          #git add _pathways/*.md
          #git add _data/*.tsv
          #if git diff --exit-code --staged > /dev/null; then
          #    echo "No changes"
          #else
          #    git commit -m 'Update tsv and md files'
          #    git push
          #fi
