name: GPML deleted. Sync repo(s) in response.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - pathways/**/*.gpml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  # inspired by https://dev.to/scienta/get-changed-files-in-github-actions-1p36
  deleted-files:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      gpml: ${{ steps.changes.outputs.gpml }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "GPML files deleted between github.event.before ${{ github.event.before }} and github.sha ${{ github.sha }} (latest)"
          #echo "github.event.after ${{ github.event.after }}"
          if git diff --name-only --diff-filter=D ${{ github.event.before }} ${{ github.sha }} | grep .gpml$; then
            git diff --name-only --diff-filter=D ${{ github.event.before }} ${{ github.sha }} | grep .gpml$
          fi
          echo "::set-output name=gpml::$(git diff --name-only --diff-filter=D ${{ github.event.before }} ${{ github.sha }} | grep .gpml$ | xargs)"
          
  sync-site-repo:
    runs-on: ubuntu-latest
    needs: deleted-files
    # only run if there are deleted files
    if: ${{needs.deleted-files.outputs.gpml}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: wikipathways-database
          submodules: true
          fetch-depth: 0
          
      - name: Checkout jekyll repo
        uses: actions/checkout@v2
        with:
          repository: wikipathways/wikipathways.github.io
          path: wikipathways.github.io
          submodules: true
          fetch-depth: 0
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}   ## for push into cookbook-dev

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          cd wikipathways.github.io
          for f in ${{needs.deleted-files.outputs.gpml}}; do
            echo "file path: $f"
            wpid="$(basename ""$f"" | sed 's/.gpml//')"
            echo "deleting $wpid from wikipathways.github.io"
            if [ -e _pathways/"$wpid".md ]; then
              git rm _pathways/"$wpid".md
            fi
            if [ -e _data/"$wpid"-bibliography.tsv ]; then
              git rm _data/"$wpid"-bibliography.tsv
            fi
            if [ -e _data/"$wpid"-datanodes.tsv ]; then
              git rm _data/"$wpid"-datanodes.tsv
            fi
          done          
          git add _pathways/*.md
          git add _data/*.tsv
          if git diff --exit-code --staged > /dev/null; then
              echo "No changes"
          else
              git commit -m 'Remove deleted tsv and md file(s)'
              git push
          fi
