name: (Debug) Handle GPML changes

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - pathways/**/*.gpml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false # to allow multiple runs to queue up rather than clobber

jobs:
  # inspired by https://dev.to/scienta/get-changed-files-in-github-actions-1p36
  changed-gpmls:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      added-modified: ${{ steps.changes.outputs.added-modified }}
      copied: ${{ steps.changes.outputs.copied }}
      deleted: ${{ steps.changes.outputs.deleted }}
      renamed: ${{ steps.changes.outputs.renamed }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "GPML files were changed in pull request ${{ github.event.before }} -> ${{ github.event.after }}"
          
          echo "::set-output name=added-modified::$(git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$ | xargs)"
          if git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$; then
            echo 'added or modified:'
            git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$
          fi
          
          echo "::set-output name=copied::$(git diff --name-only --diff-filter=C ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$ | xargs)"
          if git diff --name-only --diff-filter=C ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$; then
            echo 'copied:'
            git diff --name-only --diff-filter=C ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$
          fi

          echo "::set-output name=deleted::$(git diff --name-only --diff-filter=D ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$ | xargs)"
          if git diff --name-only --diff-filter=D ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$; then
            echo 'deleted:'
            git diff --name-only --diff-filter=D ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$
          fi
            
          echo "::set-output name=renamed::$(git diff --name-only --diff-filter=R ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$ | xargs)"
          if git diff --name-only --diff-filter=R ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$; then
            echo 'renamed:'
            git diff --name-only --diff-filter=R ${{ github.event.before }} ${{ github.event.after }} | grep .gpml$
          fi

  metadata-debug:
    runs-on: ubuntu-latest
    needs: changed-gpmls
    # only run if gpmls were added or modified
    if: ${{needs.changed-gpmls.outputs.added-modified}}
    steps:
      - name: Checkout wikipathways-database repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
        
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/
          key: ${{ runner.os }}-java-'meta-data-action-0.0.2-jar-with-dependencies.jar'
          restore-keys: |
            ${{ runner.os }}-java-

      - name: Install deps
        run: |
          if [ ! -e ./meta-data-action-0.0.2-jar-with-dependencies.jar ]; then
            wget https://github.com/wikipathways/meta-data-action/releases/download/v0.0.2/meta-data-action-0.0.2-jar-with-dependencies.jar
          fi
  
      - name: Generate info and datanode files
        run: |
          for f in ${{needs.changed-gpmls.outputs.added-modified}}; do
            wpid="$(basename ""$f"" | sed 's/.gpml//')"
            echo "generating info and datanode files for $wpid ($f)"
            # TODO: Is the following correct? Is the authentication key correct?
            java -jar meta-data-action-0.0.2-jar-with-dependencies.jar wikipathways/wikipathways-database pathways/"$wpid"/"$wpid".gpml $(date --utc +%F)
          done
      
      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add pathways/WP*/WP*.{json,tsv}
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git pull
              echo "debug success"
          fi