name: Install bridge dependencies

on:
  schedule:
  - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false # to allow multiple runs to queue up rather than clobber

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout wikipathways-database repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
            
      - name: Cache meta-data-action with dependencies
        uses: actions/cache@v3
        id: cacheMetaJar
        with:
          path: ./meta-data-action-1.0.7-jar-with-dependencies.jar
          key: cached-meta-data-action-${{ hashFiles('meta-data-action-1.0.7-jar-with-dependencies.jar') }}
          restore-keys: |
            cached-meta-data-action-${{ hashFiles('meta-data-action-1.0.7-jar-with-dependencies.jar') }}
            cached-meta-data-action-
    
      - if: steps.cacheMetaJar.outputs.cache-hit != 'true'
        name: Install deps
        run: |
          echo "Cache not found: cached-meta-data-action"
          if [ ! -e ./meta-data-action-1.0.7-jar-with-dependencies.jar ]; then
            wget -O meta-data-action-1.0.7-jar-with-dependencies.jar https://github.com/wikipathways/meta-data-action/releases/download/v1.1.0/meta-data-action-1.0.7-jar-with-dependencies.jar
          fi
              
      - name: Generate gdb.config, fileNames.config, and fileDownloads.config
        run: |
          for f in ${{needs.changed-gpmls.outputs.added-modified}}; do
            scripts/meta-data-action/configGenerator.sh $f
          done
          
      - name: Cache all bridge files
        uses: actions/cache@v2
        id: cacheAllBridge
        with:
          path: |
            ./metabolites*.bridge
            ./Mm*.bridge
          key: cached-bridge-files
          restore-keys: |
            cached-bridge-files
            
      - if: steps.cacheAllBridge.outputs.cache-hit != 'true'
      - name: Install all bridge files
        run: |
          echo "Cache not found: cached-bridge-files"
          declare -a OrganismNames=("Metabolites" "Mus musculus")
          for org in "${OrganismNames[@]}"; do
            echo "generating configuration files for "$org""
            scripts/meta-data-action/configGenerator.sh "$org"
            echo "installing bridgedb files for "$org""
            scripts/meta-data-action/installDependencies.sh "$org"
          done
