name: Install bridge dependencies

on:
  schedule:
  - cron: "*/5 * * * *"
  #- cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false # to allow multiple runs to queue up rather than clobber

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout wikipathways-database repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
            
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cacheMetaJar
        with:
          path: ./meta-data-action-1.0.3-jar-with-dependencies.jar
          key: ${{ runner.os }}-meta-data-action-1.0.3.jar
          restore-keys: |
            ${{ runner.os }}-java-meta-data-action-1.0.3.jar
    
      - if: steps.cacheMetaJar.outputs.cache-hit != 'true'
        name: Install deps
        run: |
          if [ ! -e ./meta-data-action-1.0.3-jar-with-dependencies.jar ]; then
            wget -O meta-data-action-1.0.3-jar-with-dependencies.jar https://github.com/hbasaric/meta-data-action/releases/download/v1.0.0/meta-data-action-1.0.3-jar-with-dependencies.jar
          fi
              
      - name: Generate gdb.config, fileNames.config, and fileDownloads.config
        run: |
          for f in ${{needs.changed-gpmls.outputs.added-modified}}; do
            scripts/meta-data-action/configGenerator.sh $f
          done
          
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cacheAllBridge
        with:
          path: |
            ./metabolites*.bridge
            ./Ag*.bridge
            ./An*.bridge
            ./At*.bridge
            ./Bs*.bridge
            ./Bt*.bridge
            ./Ce*.bridge
            ./Cf*.bridge
            ./Ci*.bridge
            ./Dr*.bridge
            ./Da*.bridge
            ./Dp*.bridge
            ./Dm*.bridge
            ./Ec*.bridge
            ./Gg*.bridge
            ./Fg*.bridge
            ./Gm*.bridge
            ./Hs*.bridge
            ./Hv*.bridge
            ./Ml*.bridge
            ./Mm*.bridge
            ./Mx*.bridge
            ./Oa*.bridge
            ./Ova*.bridge
            ./Oi*.bridge
            ./Oj*.bridge
            ./Pi*.bridge
            ./Pt*.bridge
            ./Qc*.bridge
            ./Rn*.bridge
            ./Sc*.bridge
            ./Sl*.bridge
            ./Ss*.bridge
            ./Vv*.bridge
            ./Xt*.bridge
            ./Zm*.bridge
          key: ${{ runner.os }}-java-${{ hashFiles('**/*.bridge') }}
          restore-keys: |
            ${{ runner.os }}-java-${{ hashFiles('**/*.bridge') }}
            ${{ runner.os }}-java-
            
      - name: Install all bridge files
        run: |
          declare -a OrganismNames=("Anopheles gambiae" "Aspergillus niger" "Arabidopsis thaliana" "Bacillus subtilis" "Bos taurus" "Caenorhabditis elegans" "Canis familiaris" "Ciona intestinalis" "Danio rerio" "Daphnia magna" "Daphnia pulex" "Drosophila melanogaster" "Escherichia coli" "Gallus gallus" "Fusarium graminearum"  "Glycine max" "Homo sapiens" "Hordeum vulgare" "Macaca mulatta" "Mus musculus" "Mycobacterium tuberculosis" "Ornithorhynchus anatinus" "Ovis aries" "Oryza indica" "Oryza japonica" "Populus trichocarpa" "Pan troglodytes" "Equus caballus" "Rattus norvegicus" "Saccharomyces cerevisiae" "Solanum lycopersicum" "Sus scrofa" "Vitis vinifera" "Xenopus tropicalis" "Zea mays")
          for org in "${OrganismNames[@]}"; do
            echo "generating configuration files for "$org""
            scripts/meta-data-action/configGenerator.sh "$org"
            echo "installing bridgedb files for "$org""
            scripts/meta-data-action/installDependencies.sh "$org"
          done
